// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfZBBaVtPvFbLbwiEYc4PewBApGSgNQDk',
    appId: '1:499220798990:web:0153ed00abe79fa7bde65f',
    messagingSenderId: '499220798990',
    projectId: 'speaksteps-cursor',
    authDomain: 'speaksteps-cursor.firebaseapp.com',
    databaseURL: 'https://speaksteps-cursor-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'speaksteps-cursor.firebasestorage.app',
    measurementId: 'G-6VX3ZL62YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv6m4lTXcMWBXRdMSpXQ4uFu427BZ5Sns',
    appId: '1:499220798990:android:86b532d0bb362ec8bde65f',
    messagingSenderId: '499220798990',
    projectId: 'speaksteps-cursor',
    databaseURL: 'https://speaksteps-cursor-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'speaksteps-cursor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcy8xHcW0csUZpVOePKtCPwdNXWadWCNk',
    appId: '1:499220798990:ios:b675a85f8dccb46fbde65f',
    messagingSenderId: '499220798990',
    projectId: 'speaksteps-cursor',
    databaseURL: 'https://speaksteps-cursor-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'speaksteps-cursor.firebasestorage.app',
    iosClientId: '499220798990-rfkpg8voebror7p6dv3gso3betr6a81c.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
