import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'providers/auth_provider.dart';
import 'router/app_router.dart';
import 'services/app_service.dart';

// TODO: Your backend developer needs to add Firebase configuration
// For web, they need to:
// 1. Create a Firebase project at https://console.firebase.google.com
// 2. Add a web app to the project
// 3. Copy the Firebase configuration object
// 4. Create a file: lib/firebase_options.dart (or use the one generated by FlutterFire CLI)
// 5. Initialize Firebase with: await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
// 6. Change useFirebase to true in lib/services/app_service.dart

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Check if we're using Firebase or Mock
  final useFirebase = ServiceFactory.useFirebase;
  
  if (useFirebase) {
    // Initialize Firebase only if using Firebase service
    try {
      await Firebase.initializeApp(
        // options: DefaultFirebaseOptions.currentPlatform, // Uncomment after Firebase setup
      );
    } catch (e) {
      print('Firebase initialization error: $e');
      print('Please configure Firebase first. See FIREBASE_SETUP.md for instructions.');
      print('Or set useFirebase = false in lib/services/app_service.dart to use mock data.');
    }
  } else {
    print('Using Mock Service - No Firebase required!');
    print('To use Firebase, set useFirebase = true in lib/services/app_service.dart');
  }

  runApp(const SpeakStepsApp());
}

/// SpeakSteps - Broca's Aphasia Therapy App
class SpeakStepsApp extends StatelessWidget {
  const SpeakStepsApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => AuthProvider(),
      child: MaterialApp.router(
        title: 'SpeakSteps - Aphasia Therapy',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color(0xFFCCA8E0),
            brightness: Brightness.light,
          ),
          useMaterial3: true,
          appBarTheme: const AppBarTheme(
            backgroundColor: Color(0xFFCCA8E0),
            foregroundColor: Colors.white,
            elevation: 0,
          ),
          cardTheme: CardThemeData(
            elevation: 2,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
          inputDecorationTheme: InputDecorationTheme(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
          elevatedButtonTheme: ElevatedButtonThemeData(
            style: ElevatedButton.styleFrom(
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),
        ),
        routerConfig: AppRouter.router,
      ),
    );
  }
}

